SELECT TABLE_SCHEMA,TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES t 
WHERE t.TABLE_TYPE = 'BASE TABLE';

SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'sysdac_instances_internal'

SELECT * FROM INFORMATION_SCHEMA.COLUMNS c ;

select * from INFORMATION_SCHEMA.TABLES t 
where t.TABLE_SCHEMA = 'dbo';

select count(*) as total_table
from INFORMATION_SCHEMA.TABLES t 
where t.TABLE_SCHEMA = 'dbo' and t.TABLE_TYPE = 'BASE TABLE' 

select c.TABLE_SCHEMA ,c.TABLE_NAME ,c.COLUMN_NAME ,c.ORDINAL_POSITION ,c.DATA_TYPE ,c.IS_NULLABLE ,c.COLUMN_DEFAULT 
from INFORMATION_SCHEMA.COLUMNS c ;

select * from INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc ;

SELECT *
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;

select *  FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS;

select * from INFORMATION_SCHEMA.VIEWS v ;